title: Security
type: documentation
changelogURL:
items:
  - date: 2021-11-05
    page: Security
    summary: Added security updates section.
    affectsContent: true
    isAddition: true
    githubPr: 1304
    githubRepo: uswds-site
    versionUswds:
